version: "3"
services:
    next-app:
        container_name: reddit-frontend
        build:
            context: .
            dockerfile: DockerfileDev

        # Set envrionment variables based on the .env file
        env_file:
            - .env
        volumes:
            - ./:/app
        ports:
            - 3000:3000
